## Hurricane Analysis

##### Project Goals
You will work to write several functions that organize and manipulate data about Category 5 Hurricanes, the strongest hurricanes as rated by their wind speed. Each one of these functions will use a number of parameters, conditionals, lists, dictionaries, string manipulation, and return statements.

In [750]:
# names of hurricanes
names = ['Cuba I', 'San Felipe II Okeechobee', 'Bahamas', 'Cuba II', 'CubaBrownsville', 'Tampico',
         'Labor Day', 'New England', 'Carol', 'Janet', 'Carla', 'Hattie', 'Beulah', 'Camille', 'Edith', 'Anita', 
         'David', 'Allen', 'Gilbert', 'Hugo', 'Andrew', 'Mitch', 'Isabel', 'Ivan', 'Emily', 'Katrina', 'Rita', 'Wilma', 
         'Dean', 'Felix', 'Matthew', 'Irma', 'Maria', 'Michael']

# months of hurricanes
months = ['October', 'September', 'September', 'November', 'August', 'September', 'September', 'September', 'September',
          'September', 'September', 'October', 'September', 'August', 'September', 'September', 'August', 'August',
          'September', 'September', 'August', 'October', 'September', 'September', 'July', 'August', 'September',
          'October', 'August', 'September', 'October', 'September', 'September', 'October']

# years of hurricanes
years = [1924, 1928, 1932, 1932, 1933, 1933, 1935, 1938, 1953, 1955, 1961, 1961, 1967, 1969, 1971, 1977, 1979, 1980, 
         1988, 1989, 1992, 1998, 2003, 2004, 2005, 2005, 2005, 2005, 2007, 2007, 2016, 2017, 2017, 2018]

# maximum sustained winds (mph) of hurricanes
max_sustained_winds = [165, 160, 160, 175, 160, 160, 185, 160, 160, 175, 175, 160, 160, 175, 160, 175, 175, 190, 
                       185, 160, 175, 180, 165, 165, 160, 175, 180, 185, 175, 175, 165, 180, 175, 160]

# areas affected by each hurricane
areas_affected = [['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'],
                  ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 
                  ['The Bahamas', 'Northeastern United States'], 
                  ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 
                  ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'], ['Jamaica', 'Yucatn Peninsula'], 
                  ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'], 
                  ['Southeastern United States', 'Northeastern United States', 'Southwestern Quebec'], 
                  ['Bermuda', 'New England', 'Atlantic Canada'], ['Lesser Antilles', 'Central America'], 
                  ['Texas', 'Louisiana', 'Midwestern United States'], ['Central America'],
                  ['The Caribbean', 'Mexico', 'Texas'], ['Cuba', 'United States Gulf Coast'],
                  ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'], ['Mexico'], 
                  ['The Caribbean', 'United States East coast'], 
                  ['The Caribbean', 'Yucatn Peninsula', 'Mexico', 'South Texas'], 
                  ['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'], 
                  ['The Caribbean', 'United States East Coast'], ['The Bahamas', 'Florida', 'United States Gulf Coast'],
                  ['Central America', 'Yucatn Peninsula', 'South Florida'],
                  ['Greater Antilles', 'Bahamas', 'Eastern United States', 'Ontario'],
                  ['The Caribbean', 'Venezuela', 'United States Gulf Coast'], 
                  ['Windward Islands', 'Jamaica', 'Mexico', 'Texas'], ['Bahamas', 'United States Gulf Coast'], 
                  ['Cuba', 'United States Gulf Coast'], ['Greater Antilles', 'Central America', 'Florida'],
                  ['The Caribbean', 'Central America'], ['Nicaragua', 'Honduras'],
                  ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast', 'Atlantic Canada'], 
                  ['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'],
                  ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic', 'Turks and Caicos Islands'],
                  ['Central America', 'United States Gulf Coast (especially Florida Panhandle)']]

# damages (USD($)) of hurricanes
damages = ['Damages not recorded', '100M', 'Damages not recorded', '40M', '27.9M', '5M', 'Damages not recorded',
           '306M', '2M', '65.8M', '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded', '1.54B', 
           '1.24B', '7.1B', '10B', '26.5B', '6.2B', '5.37B', '23.3B', '1.01B', '125B', '12B', '29.4B', 
           '1.76B', '720M', '15.1B', '64.8B', '91.6B', '25.1B']

# deaths for each hurricane
deaths = [90,4000,16,3103,179,184,408,682,5,1023,43,319,688,259,37,11,2068,269,318,107,
          65,19325,51,124,17,1836,125,87,45,133,603,138,3057,74]



##### Step 1
Hurricanes, also known as cyclones or typhoons, are one of the most powerful forces of nature on Earth. Due to climate change caused by human activity, the number and intensity of hurricanes has risen, calling for better preparation by the many communities that are devastated by them. As a concerned environmentalist, you want to look at data about the most powerful hurricanes that have occurred.

Begin by looking at the `damages`list. The list contains strings representing the total cost in USD($) caused by `34`category 5 hurricanes (wind speeds ≥ 157 mph (252 km/h )) in the Atlantic region. For some of the hurricanes, damage data was not recorded `"Damages not recorded"`, while the rest are written in the format `"Prefix-B/M"`, where `B` stands for billions (`1000000000`) and `M` stands for millions (`1000000`).

Write a function that returns a new list of updated damages where the recorded data is converted to float values and the missing data is retained as `"Damages not recorded"`.

Test your function with the data stored in `damages`.

In [751]:
print(damages)

['Damages not recorded', '100M', 'Damages not recorded', '40M', '27.9M', '5M', 'Damages not recorded', '306M', '2M', '65.8M', '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded', '1.54B', '1.24B', '7.1B', '10B', '26.5B', '6.2B', '5.37B', '23.3B', '1.01B', '125B', '12B', '29.4B', '1.76B', '720M', '15.1B', '64.8B', '91.6B', '25.1B']


In [752]:
def damage_converter(damages):
    damages_list = []
    for record in damages:    
        if record.endswith("M"):
            record = float(record[:-1]) * 1000000
            damages_list.append(record)
        elif record.endswith("B"):
            record = float(record[:-1]) * 1000000000
            damages_list.append(record)
        else:
            damages_list.append(record)
    return damages_list

In [753]:
print(damage_converter(damages))

['Damages not recorded', 100000000.0, 'Damages not recorded', 40000000.0, 27900000.0, 5000000.0, 'Damages not recorded', 306000000.0, 2000000.0, 65800000.0, 326000000.0, 60300000.0, 208000000.0, 1420000000.0, 25400000.0, 'Damages not recorded', 1540000000.0, 1240000000.0, 7100000000.0, 10000000000.0, 26500000000.0, 6200000000.0, 5370000000.0, 23300000000.0, 1010000000.0, 125000000000.0, 12000000000.0, 29400000000.0, 1760000000.0, 720000000.0, 15100000000.0, 64800000000.0, 91600000000.0, 25100000000.0]


##### Step 2
Additional data collected on the 34 strongest Atlantic hurricanes are provided in a series of lists. The data includes:

- `names`: names of the hurricanes
- `months`: months in which the hurricanes occurred
- `years`: years in which the hurricanes occurred
- `max_sustained_winds`: maximum sustained winds (miles per hour) of the hurricanes
- `areas_affected`: list of different areas affected by each of the hurricanes
- `deaths`: total number of deaths caused by each of the hurricanes<br>
The data is organized such that the data at each index, from 0 to 33, corresponds to the same hurricane.

For example, `names[0]` yields the “Cuba I” hurricane, which ouccred in `months[0]` (October) `years[0]` (1924).

Write a function that constructs a dictionary made out of the lists, where the keys of the dictionary are the names of the hurricanes, and the values are dictionaries themselves containing a key for each piece of data (`Name`, `Month`, `Year`, `Max Sustained Wind`, `Areas Affected`, `Damage`, `Death`) about the hurricane.

Thus the key `"Cuba I"` would have the value: `{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}`.

Test your function on the lists of data provided.

In [754]:
def list_to_dict(names):
    my_dict = {}
    for i in range(len(names)):
            my_dict[names[i]] ={"Name" : names[i], 
                            "Month" : months[i],
                            "Year" : years[i],
                            "Max Sustained Wind": max_sustained_winds[i],
                            "Areas Affected": areas_affected[i],
                            "Damage":damages[i],
                            "Deaths": deaths[i]}
    return my_dict

In [755]:
list_to_dict(names)

{'Cuba I': {'Name': 'Cuba I',
  'Month': 'October',
  'Year': 1924,
  'Max Sustained Wind': 165,
  'Areas Affected': ['Central America',
   'Mexico',
   'Cuba',
   'Florida',
   'The Bahamas'],
  'Damage': 'Damages not recorded',
  'Deaths': 90},
 'San Felipe II Okeechobee': {'Name': 'San Felipe II Okeechobee',
  'Month': 'September',
  'Year': 1928,
  'Max Sustained Wind': 160,
  'Areas Affected': ['Lesser Antilles',
   'The Bahamas',
   'United States East Coast',
   'Atlantic Canada'],
  'Damage': '100M',
  'Deaths': 4000},
 'Bahamas': {'Name': 'Bahamas',
  'Month': 'September',
  'Year': 1932,
  'Max Sustained Wind': 160,
  'Areas Affected': ['The Bahamas', 'Northeastern United States'],
  'Damage': 'Damages not recorded',
  'Deaths': 16},
 'Cuba II': {'Name': 'Cuba II',
  'Month': 'November',
  'Year': 1932,
  'Max Sustained Wind': 175,
  'Areas Affected': ['Lesser Antilles',
   'Jamaica',
   'Cayman Islands',
   'Cuba',
   'The Bahamas',
   'Bermuda'],
  'Damage': '40M',
  'Death

##### Step 3
In addition to organizing the hurricanes in a dictionary with names as the key, you want to be able to organize the hurricanes by year.

Write a function that converts the current dictionary of hurricanes to a new dictionary, where the keys are years and the values are lists containing a dictionary for each hurricane that occurred in that year.

For example, the key `1932` would yield the value: `[{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}]`.

Test your function on your hurricane dictionary.

In [756]:
hurricanes = list_to_dict(names)

In [757]:
def dict_to_year(hurricanes):
    new_dict = {}
    for key, value in hurricanes.items():
        new_dict[value["Year"]] = [value]
    return new_dict

In [758]:
new_dict

{1924: [{'Name': 'Cuba I',
   'Month': 'October',
   'Year': 1924,
   'Max Sustained Wind': 165,
   'Areas Affected': ['Central America',
    'Mexico',
    'Cuba',
    'Florida',
    'The Bahamas'],
   'Damage': 'Damages not recorded',
   'Deaths': 90}],
 1928: [{'Name': 'San Felipe II Okeechobee',
   'Month': 'September',
   'Year': 1928,
   'Max Sustained Wind': 160,
   'Areas Affected': ['Lesser Antilles',
    'The Bahamas',
    'United States East Coast',
    'Atlantic Canada'],
   'Damage': '100M',
   'Deaths': 4000}],
 1932: [{'Name': 'Cuba II',
   'Month': 'November',
   'Year': 1932,
   'Max Sustained Wind': 175,
   'Areas Affected': ['Lesser Antilles',
    'Jamaica',
    'Cayman Islands',
    'Cuba',
    'The Bahamas',
    'Bermuda'],
   'Damage': '40M',
   'Deaths': 3103}],
 1933: [{'Name': 'Tampico',
   'Month': 'September',
   'Year': 1933,
   'Max Sustained Wind': 160,
   'Areas Affected': ['Jamaica', 'Yucatn Peninsula'],
   'Damage': '5M',
   'Deaths': 184}],
 1935: [{'Na

##### Step 4
You believe that knowing how often each of the areas of the Atlantic are affected by these strong hurricanes is important for making preparations for future hurricanes.

Write a function that counts how often each area is listed as an affected area of a hurricane. Store and return the results in a dictionary where the keys are the affected areas and the values are counts of how many times the areas were affected.

Test your function on your hurricane dictionary.

In [759]:
print(areas_affected)

[['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], ['The Bahamas', 'Northeastern United States'], ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'], ['Jamaica', 'Yucatn Peninsula'], ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'], ['Southeastern United States', 'Northeastern United States', 'Southwestern Quebec'], ['Bermuda', 'New England', 'Atlantic Canada'], ['Lesser Antilles', 'Central America'], ['Texas', 'Louisiana', 'Midwestern United States'], ['Central America'], ['The Caribbean', 'Mexico', 'Texas'], ['Cuba', 'United States Gulf Coast'], ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'], ['Mexico'], ['The Caribbean', 'United States East coast'], ['The Caribbean', 'Yucatn Peninsula', 'Mexico', 'South Texas'], ['Jamaica', 'Venezuela', 'Central Americ

In [760]:
def hurricane_counter(areas_affected):
    new_dict = {}
    area_list = []
    for areas in areas_affected:
        for area in areas:
            area_list.append(area)
    for item in area_list:
        new_dict[item] = area_list.count(item)
    return new_dict

In [761]:
print(new_dict)

{1924: [{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}], 1928: [{'Name': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928, 'Max Sustained Wind': 160, 'Areas Affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damage': '100M', 'Deaths': 4000}], 1932: [{'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': '40M', 'Deaths': 3103}], 1933: [{'Name': 'Tampico', 'Month': 'September', 'Year': 1933, 'Max Sustained Wind': 160, 'Areas Affected': ['Jamaica', 'Yucatn Peninsula'], 'Damage': '5M', 'Deaths': 184}], 1935: [{'Name': 'Labor Day', 'Month': 'September', 'Year': 1935, 'Max Sustained Wind': 185, 'Areas Affected': ['The Bahamas', 'Florida'

##### Step 5
Write a function that finds the area affected by the most hurricanes, and how often it was hit.

Test your function on your affected area dictionary.

In [762]:
areas_affected_dict = hurricane_counter(areas_affected)

In [763]:
print(areas_affected_dict)

{'Central America': 9, 'Mexico': 7, 'Cuba': 6, 'Florida': 6, 'The Bahamas': 7, 'Lesser Antilles': 4, 'United States East Coast': 3, 'Atlantic Canada': 3, 'Northeastern United States': 2, 'Jamaica': 4, 'Cayman Islands': 1, 'Bermuda': 2, 'Texas': 4, 'Tamaulipas': 1, 'Yucatn Peninsula': 3, 'Georgia': 1, 'The Carolinas': 1, 'Virginia': 1, 'Southeastern United States': 1, 'Southwestern Quebec': 1, 'New England': 1, 'Louisiana': 1, 'Midwestern United States': 1, 'The Caribbean': 8, 'United States Gulf Coast': 6, 'United States East coast': 1, 'South Texas': 1, 'Venezuela': 3, 'Hispaniola': 1, 'South Florida': 1, 'Greater Antilles': 2, 'Bahamas': 2, 'Eastern United States': 1, 'Ontario': 1, 'Windward Islands': 1, 'Nicaragua': 1, 'Honduras': 1, 'Antilles': 1, 'Colombia': 1, 'Cape Verde': 1, 'British Virgin Islands': 1, 'U.S. Virgin Islands': 1, 'Virgin Islands': 1, 'Puerto Rico': 1, 'Dominican Republic': 1, 'Turks and Caicos Islands': 1, 'United States Gulf Coast (especially Florida Panhandle)

In [764]:
def most_affected_area(areas_affected_dict):
    counter = 0
    for area, count in areas_affected_dict.items():
        if count > counter:
            counter = count
    for key in areas_affected_dict.items():
        if key[1] == counter:
            print("Most affected area is {} and There are {} hurricane.".format(key[0], key[1]))

In [765]:
most_affected_area(areas_affected_dict)

Most affected area is Central America and There are 9 hurricane.


##### Step 6
Write a function that finds the hurricane that caused the greatest number of deaths, and how many deaths it caused.

Test your function on your hurricane dictionary.

In [766]:
def greatest_deaths(hurricanes):
    max_death = 0
    for area in hurricanes:
        if hurricanes[area]["Deaths"] > max_death:
            max_death = hurricanes[area]["Deaths"]
    for hurricane in hurricanes:
        if hurricanes[hurricane]["Deaths"] == max_death:
            print("The hurricane that caused the greatest number of deaths is {} and there are {} deaths."\
                  .format(hurricanes[hurricane]["Name"], hurricanes[hurricane]["Deaths"]))   

In [767]:
greatest_deaths(hurricanes)

The hurricane that caused the greatest number of deaths is Mitch and there are 19325 deaths.


##### Step 7
Just as hurricanes are rated by their windspeed, you want to try rating hurricanes based on other metrics.

Write a function that rates hurricanes on a mortality scale according to the following ratings, where the key is the rating and the value is the upper bound of deaths for that rating.

`mortality_scale = {0: 0, 1: 100, 2: 500, 3: 1000, 4: 10000}`<br>
For example, a hurricane with a `1` mortality rating would have resulted in greater than `0` but less than or equal to `100` deaths. A hurricane with a 5 mortality rating would have resulted in greater than `10000` deaths.

Store the hurricanes in a new dictionary where the keys are mortality ratings and the values are lists containing a dictionary for each hurricane that falls into that mortality rating.

Test your function on your hurricane dictionary.

In [768]:
def hurricane_rate_func(hurricanes):
    rate4_list = []
    rate3_list = []
    rate2_list = []
    rate1_list = []
    rate0_list = []
    hurricane_rating = {}
    for hurricane in hurricanes:
        if hurricanes[hurricane]["Deaths"] > 1000 and hurricanes[hurricane]["Deaths"] <= 10000:
            rate4_list.append(hurricanes[hurricane])
            hurricane_rating["4"] = rate4_list
        elif hurricanes[hurricane]["Deaths"] > 500 and hurricanes[hurricane]["Deaths"] <= 1000:
            rate3_list.append(hurricanes[hurricane])
            hurricane_rating["3"] = rate3_list
        elif hurricanes[hurricane]["Deaths"] > 100 and hurricanes[hurricane]["Deaths"] <= 500:
            rate2_list.append(hurricanes[hurricane])
            hurricane_rating["2"] = rate2_list
        elif hurricanes[hurricane]["Deaths"] > 0 and hurricanes[hurricane]["Deaths"] <= 100:
            rate1_list.append(hurricanes[hurricane])
            hurricane_rating["1"] = rate1_list
        elif hurricanes[hurricane]["Deaths"]  == 0:
            rate0_list.append(hurricanes[hurricane])
            hurricane_rating["0"] = rate0_list
    return hurricane_rating

In [769]:
print(hurricane_rate_func(hurricanes))

{'1': [{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}, {'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Carol', 'Month': 'September', 'Year': 1953, 'Max Sustained Wind': 160, 'Areas Affected': ['Bermuda', 'New England', 'Atlantic Canada'], 'Damage': '2M', 'Deaths': 5}, {'Name': 'Carla', 'Month': 'September', 'Year': 1961, 'Max Sustained Wind': 175, 'Areas Affected': ['Texas', 'Louisiana', 'Midwestern United States'], 'Damage': '326M', 'Deaths': 43}, {'Name': 'Edith', 'Month': 'September', 'Year': 1971, 'Max Sustained Wind': 160, 'Areas Affected': ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'], 'Damage': '25.4M', 'Deaths': 37}, {'Name': 'Anita

##### Step 8
Write a function that finds the hurricane that caused the greatest damage, and how costly it was.

Test your function on your hurricane dictionary.

In [770]:
def greatest_damage_func(hurricanes):
    names = []
    damages = []
    for hurricane in hurricanes:
        names.append(hurricanes[hurricane]["Name"])
        damages.append(hurricanes[hurricane]["Damage"])
    for i in range(len(damages)):
        if damages[i].endswith("M"):
            damages[i] = float(damages[i][:-1]) * 1000000
        elif damages[i].endswith("B"):
            damages[i] = float(damages[i][:-1]) * 1000000000
        else:
            damages[i] = 0
    for pair in zip(names, damages):
        if pair[1] == max(damages):
            print("The hurricane that caused the greatest damage is {} and cost is {}".format(pair[0], pair[1]))

In [771]:
greatest_damage_func(hurricanes)

The hurricane that caused the greatest damage is Katrina and cost is 125000000000.0
